version: '3'
services:
  vprodb:
    container_name: vprodb
    build:
      context: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vprodbpass
      MYSQL_DATABASE: accounts
    volumes:
      - vprodbdata:/var/lib/mysql

  vproapp:
    container_name: vproapp
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - vprodb

  vproweb:
    container_name: vproweb
    build:
      context: ./web
    ports:
      - "80:80"
    depends_on:
      - vproapp

volumes:
  vprodbdata:

volumes:
  vprodbdata: {}
  vproappdata: {}
